### ISSUE TITLE
Set NODE_ENV

### ISSUE THREAD

**Issue by jhnns** [peerigon/dynamic-config#9]
I think, we should set `NODE_ENV` according to  `env`. It is the node.js de-facto standard and [can even impact performance](http://apmblog.dynatrace.com/2015/07/22/the-drastic-effects-of-omitting-node_env-in-your-express-js-applications/).

**Comment by meaku** [comment]
`dynamic-config` is already checking for NODE_ENV and you can use NODE_ENV=production to load the production config. 

I think dynamic-config should only "listen" for NODE_ENV rather than setting it. That's more predictable for developers and has less side effects. Maybe we should add it to the README. 

Agree?

**Comment by meaku** [comment]
Reopen if you disagree.

**Comment by jhnns** [comment]
You're right, we should not alter `process.env`.

But I think we should replace all examples with just `env` to `NODE_ENV`. It really seems like `NODE_ENV` is a de-facto standard, even React uses it to toggle developer mode.

**Comment by benurb** [comment]
Since you both seem to agree and I'm already on it, I created a PR for this.
It's only one occurrence 😃

**Comment by benurb** [comment]
I guess this issue can be closed then?
